displayName=RuneManager
author=Zlimon
description=Sync your OSRS account data with a RuneManager instance.
tags=runemanager,hiscores,sync
version=
plugins=com.zlimon.runemanager.RuneManagerPlugin
build=standard
